Control-Cash/controlcash

- docs/documento-de-visao.md
O documento de visão iniciado na disciplina Engenharia de Software 1 foi ampliado e convertido em Markdown, os requisitos foram apenas listados e serão melhor desenvolvidos em issues que serão divididas posteriormente entre os membros da equipe.
resolve #1
> Cria base do documento de visão #1

- docs/plano-iteracoes.md
- docs/plano-releases.md
> Adiciona os planos de release e iteração #23

- docs/user-stories.md
> Lista user stories com base em requisitos #24

- .gitignore
> Adiciona gitignore #17

- README.md
- docs/documento-de-modelos.md
Atualiza o README do projeto com os links para os documentos do projeto, a definição e os tutoriais da tecnologia escolhida, conforme requisitado na tarefa do SIGAA
resolve #18
> Atualiza README com links e tutoriais #18

- docs/documento-de-modelos.md
- docs/documento-de-visao.md
Os requisitos foram formatados e alguns foram alterados para ficar conforme os demais:
Alterei o usuário Administrador para Administrador financeiro, para ficar mais claro
Alguns requisitos não especificavam os atributos da entidade, então inseri
Os atributos das entidades Produto e Venda estavam repetindo em Item de venda, então eu os removi.
> Revisa documento de visão e inicia modelo de dados

- docs/documento-de-modelos.md
Também fiz o modelo para as tabelas Taxa e TaxaFormaPagamento, pois se mostraram necessárias.
resolve #32
> Cria modelo de dados para tabelas Pagamento, FormaPagamento e Despesa

- docs/user-stories.md
> Adiciona especificação do caso de uso US01 #9

- docs/documento-de-modelos.md
Adicionei as tabelas Produto, Categoria e CategoriaProduto e suas conexões no documento de modelo de dados.
> Doc/issue31 

- docs/user-stories.md
> Atualiza requisitos envolvidos no caso de uso US01 #9

- docs/documento-de-modelos.md
Fiz algumas correções no modelo de dados.
Resolve #51
> Corrige conexões do modelo de dados

- docs/plano-iteracoes.md
> Atualiza atividades feitas na iteração 1 #53

- docs/plano-iteracoes.md
- produto/templates/formCriarProduto.html
Esqueci de colocar o atributo no form de cadastro coloquei apenas no de validação
> adicionando o required ao form de cadastro #19

- docs/user-stories.md
- produto/signals.py
- venda/models.py
- venda/tests/venda/test_models.py
- venda/tests/venda/views/test_cliente_views.py
- venda/tests/venda/views/test_item_views.py
- venda/tests/venda/views/test_venda_views.py
- venda/views/venda_views.py
resolve #73, resolve #74, resolve #76
> Implementa funcionalidades ligadas a venda (venda, cliente, item) e seus testes

- .github/workflows/django.yml
- produto/signals.py
- requirements.txt
- venda/models.py
- venda/signals.py
- venda/tests/venda/test_models.py
- venda/tests/venda/views/test_item_views.py
- venda/tests/venda/views/test_venda_views.py
- venda/views/venda_views.py
> Fix/issue85 - Corrige testes do app venda

- sonar-project.properties
Atualizei o arquivo do sonar para ele pegar a cobertura do código quando roda
> Atualiza sonar-project.properties #88

- produto/views.py
- venda/views/cliente_views.py
- venda/views/item_views.py
- venda/views/venda_views.py
> Corrige erros nas views apontados pelo sonar

- .github/workflows/django.yml
Atualiza action de testes do django para executar o sonar
> Atualiza workflow django.yml

- docs/documento-pontos-de-funcao.md
- docs/user-stories.md
> Descrever US08 - Manter cliente #98

- docs/user-stories.md
> Adiciona descrição de US08 manter cliente #98

- README.md
> Formata instruções de execução do README #97

- .env.example
- .github/workflows/django.yml
- README.md
- controlCash/settings.py
- requirements.txt
> Configura uso da aplicação com o MariaDB

- .dockerignore
- .env.example
- Dockerfile
- controlCash/settings.py
- docker-compose.yml
> Configura dockerimage e docker-compose

- templates/404.html
> Adiciona página 404 personalizada #130
